/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-15  07:24:55 AM
 */
package english.phrases;

public class CALLCENTRE_CLOSED extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for CALLCENTRE_CLOSED
	 */ 
	public CALLCENTRE_CLOSED() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("6032.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 