/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-15  07:25:46 AM
 */
package english.phrases;

public class CALLCENTER_THANKYOU extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for CALLCENTER_THANKYOU
	 */ 
	public CALLCENTER_THANKYOU() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("6105.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 