/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:44:23 PM
 */
package english.phrases;

public class CHRISTMAS extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for CHRISTMAS
	 */ 
	public CHRISTMAS() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9015.wav");
		setText("CHRISTMAS");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 