/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:39:03 PM
 */
package english.phrases;

public class HOLIDAY_EVENT extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for HOLIDAY_EVENT
	 */ 
	public HOLIDAY_EVENT() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9000.wav");
		setText("In the Event of");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 