/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:40:36 PM
 */
package english.phrases;

public class HOLIDAY_CLOSED extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for HOLIDAY_CLOSED
	 */ 
	public HOLIDAY_CLOSED() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9004.wav");
		setText("We are closed.");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 