/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:40:08 PM
 */
package english.phrases;

public class HOLIDAY_ON extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for HOLIDAY_ON
	 */ 
	public HOLIDAY_ON() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9002.wav");
		setText("On");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 