/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:39:36 PM
 */
package english.phrases;

public class HOLIDAY_HOURS extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for HOLIDAY_HOURS
	 */ 
	public HOLIDAY_HOURS() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9001.wav");
		setText("Holiday. Our Office Hours would change as follows");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 