/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:42:03 PM
 */
package english.phrases;

public class HOLIDAY_DAY extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for HOLIDAY_DAY
	 */ 
	public HOLIDAY_DAY() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9003.wav");
		setText("day");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 