/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:41:03 PM
 */
package english.phrases;

public class HOLIDAY_OPEN extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for HOLIDAY_OPEN
	 */ 
	public HOLIDAY_OPEN() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9005.wav");
		setText("We are open from");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 