/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:41:25 PM
 */
package english.phrases;

public class HOLIDAY_TO extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for HOLIDAY_TO
	 */ 
	public HOLIDAY_TO() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9006.wav");
		setText("To");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 