/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:47:11 PM
 */
package english.phrases;

public class JULY4 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for JULY4
	 */ 
	public JULY4() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9022.wav");
		setText("Independence Day");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 