/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:45:37 PM
 */
package english.phrases;

public class LABOURDAY extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for LABOURDAY
	 */ 
	public LABOURDAY() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9018.wav");
		setText("Labour Day");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 