/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:45:59 PM
 */
package english.phrases;

public class MARTIN extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for MARTIN
	 */ 
	public MARTIN() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9019.wav");
		setText("Martin Luther Kin");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 