/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:46:46 PM
 */
package english.phrases;

public class MEMORIAL extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for MEMORIAL
	 */ 
	public MEMORIAL() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9021.wav");
		setText("Memorial Day");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 