/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:45:16 PM
 */
package english.phrases;

public class NEWYEAR extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for NEWYEAR
	 */ 
	public NEWYEAR() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9017.wav");
		setText("New Year");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 