/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:46:08 PM
 */
package english.phrases;

public class PAS_4109 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4109
	 */ 
	public PAS_4109() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4109.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 