/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:44:52 PM
 */
package english.phrases;

public class PAS_4105 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4105
	 */ 
	public PAS_4105() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4105.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 