/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:44:16 PM
 */
package english.phrases;

public class PAS_4103 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4103
	 */ 
	public PAS_4103() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4103.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 