/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-AUG-20  10:49:20 AM
 */
package english.phrases;

public class PAS_TEP_NINM extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_TEP_NINM
	 */ 
	public PAS_TEP_NINM() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("3065.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 