/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:43:11 PM
 */
package english.phrases;

public class PAS_EXTN extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_EXTN
	 */ 
	public PAS_EXTN() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4100.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 