/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:43:28 PM
 */
package english.phrases;

public class PAS_HOLD extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_HOLD
	 */ 
	public PAS_HOLD() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4101.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 