/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:48:27 PM
 */
package english.phrases;

public class PAS_4118 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4118
	 */ 
	public PAS_4118() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4118.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 