/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:45:42 PM
 */
package english.phrases;

public class PAS_4108 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4108
	 */ 
	public PAS_4108() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4108.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 