/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:47:20 PM
 */
package english.phrases;

public class PAS_4113 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4113
	 */ 
	public PAS_4113() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4113.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 