/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:45:11 PM
 */
package english.phrases;

public class PAS_4106 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4106
	 */ 
	public PAS_4106() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4106.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 