/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:48:15 PM
 */
package english.phrases;

public class PAS_4117 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4117
	 */ 
	public PAS_4117() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4117.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 