/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-SEP-04  11:11:12 AM
 */
package english.phrases;

public class PAS_4120 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4120
	 */ 
	public PAS_4120() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4120.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 