/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:48:00 PM
 */
package english.phrases;

public class PAS_4116 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4116
	 */ 
	public PAS_4116() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4116.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 