/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-15  07:25:18 AM
 */
package english.phrases;

public class PAS_MEETING extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_MEETING
	 */ 
	public PAS_MEETING() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("6103.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 