/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2007-JUL-30  12:43:46 PM
 */
package english.phrases;

public class PAS_4102 extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PAS_4102
	 */ 
	public PAS_4102() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("4102.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 