/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-FEB-29  12:10:22 PM
 */
package english.phrases;

public class PORT_CLOSED extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PORT_CLOSED
	 */ 
	public PORT_CLOSED() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("6033.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 