/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:46:23 PM
 */
package english.phrases;

public class PRESIDENTS extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PRESIDENTS
	 */ 
	public PRESIDENTS() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9020.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 