/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-10  01:44:53 PM
 */
package english.phrases;

public class THANKSGIVING extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for THANKSGIVING
	 */ 
	public THANKSGIVING() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9016.wav");
		setText("Thanks Giving");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 