/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-20  05:19:47 PM
 */
package english.phrases;

public class TWP_Welcome extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for TWP_Welcome
	 */ 
	public TWP_Welcome() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9501.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 