/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-20  05:22:52 PM
 */
package english.phrases;

public class TWP_Circulation extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for TWP_Circulation
	 */ 
	public TWP_Circulation() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9505.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 