/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-20  07:25:10 PM
 */
package english.phrases;

public class TWP_ADVT_MENU extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for TWP_ADVT_MENU
	 */ 
	public TWP_ADVT_MENU() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9506.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 