/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-20  05:23:08 PM
 */
package english.phrases;

public class TWP_Hours extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for TWP_Hours
	 */ 
	public TWP_Hours() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9504.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 