/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-20  05:22:24 PM
 */
package english.phrases;

public class TWP_MainMenu extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for TWP_MainMenu
	 */ 
	public TWP_MainMenu() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9503.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 