/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-20  05:20:42 PM
 */
package english.phrases;

public class TWP_TouchTone extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for TWP_TouchTone
	 */ 
	public TWP_TouchTone() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9500.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 