/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Dialog Designer at: 2008-JAN-20  05:21:39 PM
 */
package english.phrases;

public class TWP_EXTN extends com.avaya.sce.runtime.Phrase { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for TWP_EXTN
	 */ 
	public TWP_EXTN() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setFileName("9502.wav");
		setText("");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 