package flow;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * A basic servlet which allows a user to define custom VXML code
 * Last generated by Dialog Designer at: 2008-FEB-21  09:43:01 AM
 */
public class APPLN extends com.avaya.sce.runtime.MLServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Dialog Designer at: 2008-FEB-21  09:43:01 AM
	 */
	public APPLN() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}
	
	public void requestBegin(SCESession MySession){
		
		// Variable Declarations.....
		
		ITraceInfo trace = MySession.getTraceOutput();
		
		String DNIS=MySession.getVariable(IProjectVariables.DNIS).getSimpleVariable().getStringValue();
	
		String propertiesPath=MySession.getAbsoluteProjectFilePath()+File.separator+"data"+File.separator+"ddlog4j.properties";
	//	String msgoftheDayPath = "/beadata/ites/config/esdomain92/applications/telephony/portAlloc/"+"config"+File.separator+"mday.cfg";
	//	String logPath=MySession.getAbsoluteProjectFilePath()+File.separator+"config"+File.separator+"log.cfg";
		String read_line=null;
		String data[]=null;
		String APPLNAME=null;
		
		String logFilePath=null;
		
		BufferedReader configFile=null;
		BufferedReader GlobalConfigFile=null;
		String dataPaths[]=null;
		
		
    	
    	
		try{
			
	    	Properties prop = new Properties();
	    	
	    	prop.load(new FileInputStream(propertiesPath));
	    	
	    	String CONFIGPATH=prop.getProperty("ConfigPath");
	    	String REPORT=prop.getProperty("Report");
	    	String SYSTEM=prop.getProperty("System");
	    	String TRANSFER=prop.getProperty("Transfer");
	    	
					MySession.getVariable(IProjectVariables.CONFIGPATH).getSimpleVariable().setValue(CONFIGPATH);
					
					trace.writeln(ITraceInfo.TRACE_LEVEL_FATAL, "Config Path-->"+CONFIGPATH);

					MySession.getVariable(IProjectVariables.REPORTPATH).getSimpleVariable().setValue(REPORT);
					
					trace.writeln(ITraceInfo.TRACE_LEVEL_FATAL, "Report Path-->"+REPORT);

					MySession.getVariable(IProjectVariables.SYSTEMNAME).getSimpleVariable().setValue(SYSTEM);
					
					trace.writeln(ITraceInfo.TRACE_LEVEL_FATAL, "System Name-->"+SYSTEM);

					MySession.getVariable(IProjectVariables.TRANSFER).getSimpleVariable().setValue(TRANSFER);
					
					trace.writeln(ITraceInfo.TRACE_LEVEL_FATAL, "Transfer Mode-->"+TRANSFER);
	
			
			String ConfigPath = "";
			ConfigPath=MySession.getVariable(IProjectVariables.CONFIGPATH).getSimpleVariable().getStringValue()
						+File.separator+"Allocate"+ File.separator + "applications.cfg";
			configFile=new BufferedReader(new FileReader(ConfigPath));
			
		//	System.out.println("ConfigPath="+ConfigPath);
			while((read_line=configFile.readLine())!= null)
			{
				 data=read_line.split("\\,");
				 
		//		 System.out.println("ConfigPath data[0]="+data[0]);
				 
				 if(DNIS.equalsIgnoreCase(data[0]))
	        	  {
					 MySession.getVariable(IProjectVariables.GRPNAME).getSimpleVariable().setValue(data[1]);
					 MySession.getVariable(IProjectVariables.APPNAME).getSimpleVariable().setValue(data[2]);
					 APPLNAME=data[2];
					 MySession.getVariable(IProjectVariables.EXTN).getSimpleVariable().setValue(data[3]);
					 MySession.getVariable(IProjectVariables.VDNMENU).getSimpleVariable().setValue(data[4]);
					 MySession.getVariable(IProjectVariables.LOGFILE).getSimpleVariable().setValue(data[5]);
					 MySession.getVariable(IProjectVariables.CALL_CENTER).getSimpleVariable().setValue(data[0]);
					 break;
	        	  }
				 else
				 {
					 MySession.getVariable(IProjectVariables.APPNAME).getSimpleVariable().setValue("NOAPP");
				 }
			}
			configFile.close();
			
	//    Message of the Day 	
			
			
		String msgoftheDayPath = MySession.getVariable(IProjectVariables.CONFIGPATH).getSimpleVariable().getStringValue()
		+File.separator+"Allocate"+File.separator+APPLNAME+".msgday";
			
		File workingHour=new File(msgoftheDayPath);

		if(workingHour.exists())
		{
		BufferedReader mDayFile=new BufferedReader(new FileReader(msgoftheDayPath));
		
		while ((read_line = mDayFile.readLine())!=null)
		{
			MySession.getVariable(IProjectVariables.MSGOFDAY).getSimpleVariable().setValue(read_line);
		}
		mDayFile.close();
		}
		
			
		}
		catch(Exception e)
		{
			String exception_err = e.getMessage();
			
			if ( configFile!=null){try {
				configFile.close();
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				//e1.printStackTrace();
			}}

			e.printStackTrace();
		}
		
	}


	/**
	 * Returns the submit item that identifies the next form to transition to.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Dialog Designer at: 2010-SEP-03  03:14:26 PM
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = null;
		submit = new com.avaya.sce.runtime.Submit("tepstop");
		return submit;
	}
}
