package flow;

/**
 * This interface is used to define the name of variables that are 
 * declared in the call flow.  All variables are defined as 
 * <code>public static final String</code>, which allows user-defined
 * code to reference variable names by the Java variable name.
 * Last generated by Dialog Designer at: 2007-JAN-30  09:53:09 AM
 */
public interface IProjectVariables {





	//{{START:PROJECT:VARIABLES
	/**
	 * This is a reserved block of variable name definitions.
	 * The variable names defined here can be used as the key
	 * to get the <code>com.avaya.sce.runtime.Variable</code>
	 * from the <code>SCESession</code> at runtime.<br>
	 * 
	 * For example, given a variable name <code>phoneNum</code>,
	 * user-defined code should access the variable in this format:<PRE>
	 *   Variable phNum = mySession.getVariable(IProjectVariables.PHONE_NUM);
	 *   if ( phNum != null ) {
	 *        // do something with the variable
	 *   }</PRE>
	 * 
	 * This block of code is generated automatically by Dialog Designer and should not
	 * be manually edited as changes may be overwritten by future code generation.
	 * Last generated by Dialog Designer at: 2010-SEP-03  03:14:27 PM
	 */
	public static final String EXTN = "EXTN";
	public static final String TIME = "time";
	public static final String REDIRECTINFO = "redirectinfo";
	public static final String CONFIGPATH = "CONFIGPATH";
	public static final String WORKDAY_3 = "WORKDAY3";
	public static final String MSGDAYPATH = "MSGDAYPATH";
	public static final String WORKDAY_1 = "WORKDAY1";
	public static final String WORKDAY_2 = "WORKDAY2";
	public static final String CALLID = "Callid";
	public static final String SESSION = "session";
	public static final String MEETING_TIME = "meetingTime";
	public static final String CIRCMENU = "CIRCMENU";
	public static final String GRPNAME = "GRPNAME";
	public static final String MENU_DISPLAY = "MENU_DISPLAY";
	public static final String TRANSFER = "TRANSFER";
	public static final String TEMP = "TEMP";
	public static final String DATE = "date";
	public static final String LOGFILE = "LOGFILE";
	public static final String DNIS = "DNIS";
	public static final String TRIES = "TRIES";
	public static final String HOLIDAY = "HOLIDAY";
	public static final String ADVTMENU = "ADVTMENU";
	public static final String UNIQUEID = "UNIQUEID";
	public static final String CLCT__8_0_0_EXTN = "CLCT_800_EXTN";
	public static final String APPVDN = "APPVDN";
	public static final String XFERFLAG = "XFERFLAG";
	public static final String APPNAME = "APPNAME";
	public static final String CALL_CENTER = "CallCenter";
	public static final String PAS_TEP = "PAS_TEP";
	public static final String HOLI_DAY = "HOLI_DAY";
	public static final String NO_OF_PRE_CLOSE = "NO_OF_PRE_CLOSE";
	public static final String MENU_NODNIS = "MENU_NODNIS";
	public static final String DD_LAST_EXCEPTION = "ddLastException";
	public static final String CONVRSNT_MENU = "CONVRSNT_MENU";
	public static final String MAINMENU = "MAINMENU";
	public static final String MSGOFDAY = "MSGOFDAY";
	public static final String PRECLORESPONSE = "PRECLORESPONSE";
	public static final String CLCT_EXTN = "CLCT_EXTN";
	public static final String PRECLOS = "PRECLOS";
	public static final String SYSTEMNAME = "SYSTEMNAME";
	public static final String REPORTPATH = "REPORTPATH";
	public static final String VDNMENU = "VDNMENU";
	public static final String GETDNISOBJ = "GETDNISOBJ";
	public static final String PASTEP = "PASTEP";
	public static final String EXTNTRANSFER = "EXTNTRANSFER";
	public static final String EXTNOPT = "EXTNOPT";
	public static final String TWPXFER = "TWPXFER";
	public static final String SHAREDUUI = "shareduui";
	public static final String MENU_C_2C = "MENU_C2C";
	public static final String EXTENSION = "EXTENSION";
	//}}END:PROJECT:VARIABLES
	//{{START:PROJECT:VARIABLEFIELDS
	public static final String TIME_FIELD_AUDIO = "audio";
	public static final String TIME_FIELD_HOUR = "hour";
	public static final String TIME_FIELD_MILLISECOND = "millisecond";
	public static final String TIME_FIELD_MINUTE = "minute";
	public static final String TIME_FIELD_SECOND = "second";
	public static final String TIME_FIELD_TIMEZONE = "timezone";
	public static final String REDIRECTINFO_FIELD_PRESENTATIONINFO = "presentationinfo";
	public static final String REDIRECTINFO_FIELD_REASON = "reason";
	public static final String REDIRECTINFO_FIELD_SCREENINGINFO = "screeninginfo";
	public static final String REDIRECTINFO_FIELD_URI = "uri";
	public static final String WORKDAY_3_FIELD_ENDTIME = "ENDTIME";
	public static final String WORKDAY_3_FIELD_STARTTIME = "STARTTIME";
	public static final String WORKDAY_3_FIELD_WORKDAY = "WORKDAY";
	public static final String WORKDAY_1_FIELD_ENDTIME = "ENDTIME";
	public static final String WORKDAY_1_FIELD_STARTTIME = "STARTTIME";
	public static final String WORKDAY_1_FIELD_WORKDAY = "WORKDAY";
	public static final String WORKDAY_2_FIELD_ENDTIME = "ENDTIME";
	public static final String WORKDAY_2_FIELD_STARTTIME = "STARTTIME";
	public static final String WORKDAY_2_FIELD_WORKDAY = "WORKDAY";
	public static final String SESSION_FIELD_AAI = "aai";
	public static final String SESSION_FIELD_ANI = "ani";
	public static final String SESSION_FIELD_CALLTAG = "calltag";
	public static final String SESSION_FIELD_CHANNEL = "channel";
	public static final String SESSION_FIELD_CURRENTLANGUAGE = "currentlanguage";
	public static final String SESSION_FIELD_DNIS = "dnis";
	public static final String SESSION_FIELD_LASTERROR = "lasterror";
	public static final String SESSION_FIELD_PROTOCOLNAME = "protocolname";
	public static final String SESSION_FIELD_PROTOCOLVERSION = "protocolversion";
	public static final String SESSION_FIELD_SESSIONID = "sessionid";
	public static final String SESSION_FIELD_SESSIONLABEL = "sessionlabel";
	public static final String SESSION_FIELD_SHAREDMODE = "sharedmode";
	public static final String SESSION_FIELD_UUI = "uui";
	public static final String SESSION_FIELD_VPCALLEDEXTENSION = "vpcalledextension";
	public static final String SESSION_FIELD_VPCONVERSEONDATA = "vpconverseondata";
	public static final String SESSION_FIELD_VPCOVERAGEREASON = "vpcoveragereason";
	public static final String SESSION_FIELD_VPCOVERAGETYPE = "vpcoveragetype";
	public static final String SESSION_FIELD_VPRDNIS = "vprdnis";
	public static final String SESSION_FIELD_VPREPORTURL = "vpreporturl";
	public static final String CIRCMENU_FIELD_CONFIDENCE = "confidence";
	public static final String CIRCMENU_FIELD_INPUTMODE = "inputmode";
	public static final String CIRCMENU_FIELD_INTERPRETATION = "interpretation";
	public static final String CIRCMENU_FIELD_UTTERANCE = "utterance";
	public static final String CIRCMENU_FIELD_VALUE = "value";
	public static final String MENU_DISPLAY_FIELD_CONFIDENCE = "confidence";
	public static final String MENU_DISPLAY_FIELD_INPUTMODE = "inputmode";
	public static final String MENU_DISPLAY_FIELD_INTERPRETATION = "interpretation";
	public static final String MENU_DISPLAY_FIELD_UTTERANCE = "utterance";
	public static final String MENU_DISPLAY_FIELD_VALUE = "value";
	public static final String DATE_FIELD_AUDIO = "audio";
	public static final String DATE_FIELD_DAYOFMONTH = "dayofmonth";
	public static final String DATE_FIELD_DAYOFWEEK = "dayofweek";
	public static final String DATE_FIELD_DAYOFWEEKNUM = "dayofweeknum";
	public static final String DATE_FIELD_DAYOFYEAR = "dayofyear";
	public static final String DATE_FIELD_MONTH = "month";
	public static final String DATE_FIELD_MONTHINYEAR = "monthinyear";
	public static final String DATE_FIELD_YEAR = "year";
	public static final String HOLIDAY_FIELD_ENDTIME = "ENDTIME";
	public static final String HOLIDAY_FIELD_HOLIDATE = "HOLIDATE";
	public static final String HOLIDAY_FIELD_STARTTIME = "STARTTIME";
	public static final String ADVTMENU_FIELD_CONFIDENCE = "confidence";
	public static final String ADVTMENU_FIELD_INPUTMODE = "inputmode";
	public static final String ADVTMENU_FIELD_INTERPRETATION = "interpretation";
	public static final String ADVTMENU_FIELD_UTTERANCE = "utterance";
	public static final String ADVTMENU_FIELD_VALUE = "value";
	public static final String CLCT__8_0_0_EXTN_FIELD_CONFIDENCE = "confidence";
	public static final String CLCT__8_0_0_EXTN_FIELD_INPUTMODE = "inputmode";
	public static final String CLCT__8_0_0_EXTN_FIELD_INTERPRETATION = "interpretation";
	public static final String CLCT__8_0_0_EXTN_FIELD_UTTERANCE = "utterance";
	public static final String CLCT__8_0_0_EXTN_FIELD_VALUE = "value";
	public static final String PAS_TEP_FIELD_GOBACK = "GOBACK";
	public static final String MENU_NODNIS_FIELD_COLUMN_0 = "Column0";
	public static final String MENU_NODNIS_FIELD_CONFIDENCE = "confidence";
	public static final String MENU_NODNIS_FIELD_INPUTMODE = "inputmode";
	public static final String MENU_NODNIS_FIELD_INTERPRETATION = "interpretation";
	public static final String MENU_NODNIS_FIELD_UTTERANCE = "utterance";
	public static final String MENU_NODNIS_FIELD_VALUE = "value";
	public static final String DD_LAST_EXCEPTION_FIELD_ERRORCODE = "errorcode";
	public static final String DD_LAST_EXCEPTION_FIELD_MESSAGE = "message";
	public static final String DD_LAST_EXCEPTION_FIELD_OBJECT = "object";
	public static final String DD_LAST_EXCEPTION_FIELD_STACKTRACE = "stacktrace";
	public static final String DD_LAST_EXCEPTION_FIELD_TYPE = "type";
	public static final String CONVRSNT_MENU_FIELD_CONFIDENCE = "confidence";
	public static final String CONVRSNT_MENU_FIELD_INPUTMODE = "inputmode";
	public static final String CONVRSNT_MENU_FIELD_INTERPRETATION = "interpretation";
	public static final String CONVRSNT_MENU_FIELD_UTTERANCE = "utterance";
	public static final String CONVRSNT_MENU_FIELD_VALUE = "value";
	public static final String MAINMENU_FIELD_CONFIDENCE = "confidence";
	public static final String MAINMENU_FIELD_INPUTMODE = "inputmode";
	public static final String MAINMENU_FIELD_INTERPRETATION = "interpretation";
	public static final String MAINMENU_FIELD_UTTERANCE = "utterance";
	public static final String MAINMENU_FIELD_VALUE = "value";
	public static final String CLCT_EXTN_FIELD_CONFIDENCE = "confidence";
	public static final String CLCT_EXTN_FIELD_INPUTMODE = "inputmode";
	public static final String CLCT_EXTN_FIELD_INTERPRETATION = "interpretation";
	public static final String CLCT_EXTN_FIELD_UTTERANCE = "utterance";
	public static final String CLCT_EXTN_FIELD_VALUE = "value";
	public static final String GETDNISOBJ_FIELD_RET_1 = "ret1";
	public static final String GETDNISOBJ_FIELD_RET_VAL = "retVal";
	public static final String PASTEP_FIELD_GOBACK = "GOBACK";
	public static final String SHAREDUUI_FIELD_ID = "id";
	public static final String SHAREDUUI_FIELD_VALUE = "value";
	public static final String MENU_C_2C_FIELD_COLUMN_0 = "Column0";
	public static final String MENU_C_2C_FIELD_CONFIDENCE = "confidence";
	public static final String MENU_C_2C_FIELD_INPUTMODE = "inputmode";
	public static final String MENU_C_2C_FIELD_INTERPRETATION = "interpretation";
	public static final String MENU_C_2C_FIELD_UTTERANCE = "utterance";
	public static final String MENU_C_2C_FIELD_VALUE = "value";
	//}}END:PROJECT:VARIABLEFIELDS
}
