/**
 * Last generated by Dialog Designer at: 2008-JAN-10  01:47:32 PM
 */
package english.prompts;

public class PRECLOSURE extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PRECLOSURE.
	 */
	public PRECLOSURE() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Dialog Designer at: 2010-SEP-03  03:00:56 PM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("PRECLOSURE");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_EVENT"));

		if ( new com.avaya.sce.runtime.Condition( "condition", "HOLI_DAY", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "CHRISTMAS", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"CHRISTMAS"));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "HOLI_DAY", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "THANKS", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"THANKSGIVING"));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "HOLI_DAY", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "NEWYEAR", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"NEWYEAR"));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "HOLI_DAY", com.avaya.sce.runtime.Condition.STRING_EQUAL, "LABOUR", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"LABOURDAY"));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "HOLI_DAY", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "MARTIN", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"MARTIN"));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "HOLI_DAY", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "PRESIDENTS", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"PRESIDENTS"));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "HOLI_DAY", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "MEMORIAL", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"MEMORIAL"));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "HOLI_DAY", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "JULY4", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"JULY4"));
		}

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_HOURS"));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_ON"));

		format = new com.avaya.sce.runtime.Format();
		format.add("format","date");
		format.add("Month Type","spokenmonth");
		format.add("Date Format","DMSPDYY");
		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"HOLIDAY:HOLIDATE", format));

		if ( new com.avaya.sce.runtime.Condition( "condition", "HOLIDAY:STARTTIME", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "CLOSED", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_CLOSED"));
		}
		else {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_OPEN"));
			format = new com.avaya.sce.runtime.Format();
			format.add("format","time");
			format.add("Time Format","THMAM");
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"HOLIDAY:STARTTIME", format));
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_TO"));
			format = new com.avaya.sce.runtime.Format();
			format.add("format","time");
			format.add("Time Format","THMAM");
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"HOLIDAY:ENDTIME", format));
		}

		if ( new com.avaya.sce.runtime.Condition( "condition", "NO_OF_PRE_CLOSE", com.avaya.sce.runtime.Condition.INT_EQUAL, "1", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_ON"));
			format = new com.avaya.sce.runtime.Format();
			format.add("format","date");
			format.add("Month Type","spokenmonth");
			format.add("Date Format","DMSPDYY");
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY1:WORKDAY", format));
			if ( new com.avaya.sce.runtime.Condition( "condition", "WORKDAY1:STARTTIME", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "CLOSED", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_CLOSED"));
			}
			else {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_OPEN"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY1:STARTTIME", format));
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_TO"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY1:ENDTIME", format));
			}
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "NO_OF_PRE_CLOSE", com.avaya.sce.runtime.Condition.INT_EQUAL, "2", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_ON"));
			format = new com.avaya.sce.runtime.Format();
			format.add("format","date");
			format.add("Month Type","spokenmonth");
			format.add("Date Format","DMSPDYY");
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY1:WORKDAY", format));
			if ( new com.avaya.sce.runtime.Condition( "condition", "WORKDAY1:STARTTIME", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "CLOSED", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_CLOSED"));
			}
			else {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_OPEN"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY1:STARTTIME", format));
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_TO"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY1:ENDTIME", format));
			}
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_ON"));
			format = new com.avaya.sce.runtime.Format();
			format.add("format","date");
			format.add("Month Type","spokenmonth");
			format.add("Date Format","DMSPDYY");
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY2:WORKDAY", format));
			if ( new com.avaya.sce.runtime.Condition( "condition", "WORKDAY2:STARTTIME", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "CLOSED", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_CLOSED"));
			}
			else {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_OPEN"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY2:STARTTIME", format));
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_TO"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY2:ENDTIME", format));
			}
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "NO_OF_PRE_CLOSE", com.avaya.sce.runtime.Condition.INT_EQUAL, "3", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_ON"));
			format = new com.avaya.sce.runtime.Format();
			format.add("format","date");
			format.add("Month Type","spokenmonth");
			format.add("Date Format","DMSPDYY");
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY1:WORKDAY", format));
			if ( new com.avaya.sce.runtime.Condition( "condition", "WORKDAY1:STARTTIME", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "CLOSED", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_CLOSED"));
			}
			else {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_OPEN"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY1:STARTTIME", format));
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_TO"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY1:ENDTIME", format));
			}
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_ON"));
			format = new com.avaya.sce.runtime.Format();
			format.add("format","date");
			format.add("Month Type","spokenmonth");
			format.add("Date Format","DMSPDYY");
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY2:WORKDAY", format));
			if ( new com.avaya.sce.runtime.Condition( "condition", "WORKDAY2:STARTTIME", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "CLOSED", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_CLOSED"));
			}
			else {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_OPEN"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY2:STARTTIME", format));
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_TO"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY2:ENDTIME", format));
			}
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_ON"));
			format = new com.avaya.sce.runtime.Format();
			format.add("format","date");
			format.add("Month Type","spokenmonth");
			format.add("Date Format","DMSPDYY");
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY3:WORKDAY", format));
			if ( new com.avaya.sce.runtime.Condition( "condition", "WORKDAY3:STARTTIME", com.avaya.sce.runtime.Condition.STRING_EQUAL_IGNORE, "CLOSED", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_CLOSED"));
			}
			else {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_OPEN"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY3:STARTTIME", format));
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASE,"HOLIDAY_TO"));
				format = new com.avaya.sce.runtime.Format();
				format.add("format","time");
				format.add("Time Format","THMAM");
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"WORKDAY3:ENDTIME", format));
			}
		}

	}}
