package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Dialog Designer at: 2007-JUL-30  01:42:08 PM
 */
public class PAS_EMPLOYMENT_AD extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for PAS_EMPLOYMENT_AD.
    */
    public PAS_EMPLOYMENT_AD() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(false);
        setFileName("PAS_EMPLOYMENT_AD.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

