package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Dialog Designer at: 2007-AUG-22  05:28:08 PM
 */
public class TEP_NEWSPAPER extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for TEP_NEWSPAPER.
    */
    public TEP_NEWSPAPER() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(false);
        setFileName("TEP_NEWSPAPER.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

