package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Dialog Designer at: 2007-SEP-04  11:13:44 AM
 */
public class TEP_ADVERTISING extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for TEP_ADVERTISING.
    */
    public TEP_ADVERTISING() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(false);
        setFileName("TEP_ADVERTISING.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

